on: pull_request

jobs:
  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.0'
      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: |
          ./vendor/bin/phpunit . --coverage-text=coverage.log
      - uses: actions/github-script@v3
          with:
            script: |
              const fs = require('fs');

              var coverage = fs.readFileSync('coverage.log','utf8');

              await github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: coverage
              })
